 
export const LOAD_POST_PETS = "LOAD_POST_PETS";
export const POST_PETS_RESPONSE_RECEIVED = "POST_PETS_RESPONSE_RECEIVED"; 
export const PUT_PETS_RESPONSE_RECEIVED = "PUT_PETS_RESPONSE_RECEIVED"; 
export const POST_PETS_ERROR_RECEIVED = 'POST_PETS_ERROR_RECEIVED'; 
export const PUT_PETS_ERROR_RECEIVED = 'PUT_PETS_ERROR_RECEIVED'; 

export const API_NETWORK_FAILURE = 'API_NETWORK_FAILURE'; 
export const API_FETCH_COMPLETE = 'API_FETCH_COMPLETE'; 
export const API_FETCH = 'API_FETCH'; 
export const API_FETCH_FAILURE = 'API_FETCH_FAILURE'; 